const result_enum = enum(c_int) {
    no_error = c.LXW_NO_ERROR,
    memory_malloc_failed = c.LXW_ERROR_MEMORY_MALLOC_FAILED,
    creating_xlsx_file = c.LXW_ERROR_CREATING_XLSX_FILE,
    creating_tmpfile = c.LXW_ERROR_CREATING_TMPFILE,
    reading_tmpfile = c.LXW_ERROR_READING_TMPFILE,
    zip_file_operation = c.LXW_ERROR_ZIP_FILE_OPERATION,
    zip_parameter_error = c.LXW_ERROR_ZIP_PARAMETER_ERROR,
    zip_bad_zip_file = c.LXW_ERROR_ZIP_BAD_ZIP_FILE,
    zip_internal_error = c.LXW_ERROR_ZIP_INTERNAL_ERROR,
    zip_file_add = c.LXW_ERROR_ZIP_FILE_ADD,
    zip_close = c.LXW_ERROR_ZIP_CLOSE,
    feature_not_supported = c.LXW_ERROR_FEATURE_NOT_SUPPORTED,
    null_parameter_ignored = c.LXW_ERROR_NULL_PARAMETER_IGNORED,
    parameter_validation = c.LXW_ERROR_PARAMETER_VALIDATION,
    parameter_is_empty = c.LXW_ERROR_PARAMETER_IS_EMPTY,
    sheetname_length_exceeded = c.LXW_ERROR_SHEETNAME_LENGTH_EXCEEDED,
    invalid_sheetname_character = c.LXW_ERROR_INVALID_SHEETNAME_CHARACTER,
    sheetname_start_end_apostrophe = c.LXW_ERROR_SHEETNAME_START_END_APOSTROPHE,
    sheetname_already_used = c.LXW_ERROR_SHEETNAME_ALREADY_USED,
    string_32_length_exceeded = c.LXW_ERROR_32_STRING_LENGTH_EXCEEDED,
    string_128_length_exceeded = c.LXW_ERROR_128_STRING_LENGTH_EXCEEDED,
    string_255_length_exceeded = c.LXW_ERROR_255_STRING_LENGTH_EXCEEDED,
    string_max_length_exceeded = c.LXW_ERROR_MAX_STRING_LENGTH_EXCEEDED,
    shared_string_index_not_found = c.LXW_ERROR_SHARED_STRING_INDEX_NOT_FOUND,
    worksheet_index_out_of_range = c.LXW_ERROR_WORKSHEET_INDEX_OUT_OF_RANGE,
    worksheet_max_url_length_exceeded = c.LXW_ERROR_WORKSHEET_MAX_URL_LENGTH_EXCEEDED,
    workseet_max_number_urls_exceeded = c.LXW_ERROR_WORKSHEET_MAX_NUMBER_URLS_EXCEEDED,
    image_dimensions = c.LXW_ERROR_IMAGE_DIMENSIONS,
    _,
};

pub const XlsxError = error{
    MemoryMallocFailed,
    CreatingXlsxFile,
    CreatingTmpfile,
    ReadingTmpfile,
    ZipFileOperation,
    ZipParameterError,
    ZipBadZipFile,
    ZipInternalError,
    ZipFileAdd,
    ZipClose,
    FeatureNotSupported,
    NullParameterIgnored,
    ParameterValidation,
    ParameterIsEmpty,
    SheetnameLengthExceeded,
    InvalidSheetnameCharacter,
    SheetnameStartEndApostrophe,
    SheetnameAlreadyUsed,
    String32LengthExceeded,
    String128LengthExceeded,
    String255LengthExceeded,
    StringMaxLengthExceeded,
    SharedStringIndexNotFound,
    WorksheetIndexOutOfRange,
    WorksheetMaxUrlLengthExceeded,
    WorkseetMaxNumberUrlsExceeded,
    ImageDimensions,
    UnknownError,
    NewWorkBook,
    AddWorkSheet,
    GetWorkSheetName,
    GetWorkSheets,
    AddChartSheet,
    GetChartSheetName,
    GetChartSheets,
    AddFormat,
    AddChart,
    ChartAddSeries,
    WriteRichString,
    AddTable,
};

pub inline fn checkResult(error_code: c_uint) XlsxError!void {
    const result: result_enum = @enumFromInt(error_code);
    if (result == .no_error) return;
    return switch (result) {
        .memory_malloc_failed => XlsxError.MemoryMallocFailed,
        .creating_xlsx_file => XlsxError.CreatingXlsxFile,
        .creating_tmpfile => XlsxError.CreatingTmpfile,
        .reading_tmpfile => XlsxError.ReadingTmpfile,
        .zip_file_operation => XlsxError.ZipFileOperation,
        .zip_parameter_error => XlsxError.ZipParameterError,
        .zip_bad_zip_file => XlsxError.ZipBadZipFile,
        .zip_internal_error => XlsxError.ZipInternalError,
        .zip_file_add => XlsxError.ZipFileAdd,
        .zip_close => XlsxError.ZipClose,
        .feature_not_supported => XlsxError.FeatureNotSupported,
        .null_parameter_ignored => XlsxError.NullParameterIgnored,
        .parameter_validation => XlsxError.ParameterValidation,
        .parameter_is_empty => XlsxError.ParameterIsEmpty,
        .sheetname_length_exceeded => XlsxError.SheetnameLengthExceeded,
        .invalid_sheetname_character => XlsxError.InvalidSheetnameCharacter,
        .sheetname_start_end_apostrophe => XlsxError.SheetnameStartEndApostrophe,
        .sheetname_already_used => XlsxError.SheetnameAlreadyUsed,
        .string_32_length_exceeded => XlsxError.String32LengthExceeded,
        .string_128_length_exceeded => XlsxError.String128LengthExceeded,
        .string_255_length_exceeded => XlsxError.String255LengthExceeded,
        .string_max_length_exceeded => XlsxError.StringMaxLengthExceeded,
        .shared_string_index_not_found => XlsxError.SharedStringIndexNotFound,
        .worksheet_index_out_of_range => XlsxError.WorksheetIndexOutOfRange,
        .worksheet_max_url_length_exceeded => XlsxError.WorksheetMaxUrlLengthExceeded,
        .workseet_max_number_urls_exceeded => XlsxError.WorkseetMaxNumberUrlsExceeded,
        .image_dimensions => XlsxError.ImageDimensions,
        else => XlsxError.UnknownError,
    };
}

pub inline fn strError(err: anyerror) []const u8 {
    const error_code: ?result_enum = switch (err) {
        error.MemoryMallocFailed => .memory_malloc_failed,
        error.CreatingXlsxFile => .creating_xlsx_file,
        error.CreatingTmpfile => .creating_tmpfile,
        error.ReadingTmpfile => .reading_tmpfile,
        error.ZipFileOperation => .zip_file_operation,
        error.ZipParameterError => .zip_parameter_error,
        error.ZipBadZipFile => .zip_bad_zip_file,
        error.ZipInternalError => .zip_internal_error,
        error.ZipFileAdd => .zip_file_add,
        error.ZipClose => .zip_close,
        error.FeatureNotSupported => .feature_not_supported,
        error.NullParameterIgnored => .null_parameter_ignored,
        error.ParameterValidation => .parameter_validation,
        error.ParameterIsEmpty => .parameter_is_empty,
        error.SheetnameLengthExceeded => .sheetname_length_exceeded,
        error.InvalidSheetnameCharacter => .invalid_sheetname_character,
        error.SheetnameStartEndApostrophe => .sheetname_start_end_apostrophe,
        error.SheetnameAlreadyUsed => .sheetname_already_used,
        error.String32LengthExceeded => .string_32_length_exceeded,
        error.String128LengthExceeded => .string_128_length_exceeded,
        error.String255LengthExceeded => .string_255_length_exceeded,
        error.StringMaxLengthExceeded => .string_max_length_exceeded,
        error.SharedStringIndexNotFound => .shared_string_index_not_found,
        error.WorksheetIndexOutOfRange => .worksheet_index_out_of_range,
        error.WorksheetMaxUrlLengthExceeded => .worksheet_max_url_length_exceeded,
        error.WorkseetMaxNumberUrlsExceeded => .workseet_max_number_urls_exceeded,
        error.ImageDimensions => .image_dimensions,
        else => null,
    };
    if (error_code) |code| {
        return std.mem.span(c.lxw_strerror(@intCast(@intFromEnum(code))));
    } else return switch (err) {
        error.NewWorkBook => "new_workbook() returned a null pointer.",
        error.AddWorkSheet => "add_worksheet() returned a null pointer.",
        error.GetWorkSheetName => "Could Not get WorkSheet with provided name.",
        error.GetWorkSheets => "No Allocator provided to initWorkBook(), getWorkSheets() cannot be called.",
        error.AddChartSheet => "add_chartsheet() returned a null pointer.",
        error.GetChartSheetName => "Could Not get ChartSheet with provided name.",
        error.GetChartSheets => "No Allocator provided to initWorkBook(), getChartSheets() cannot be called.",
        error.AddFormat => "add_format() returned a null pointer.",
        error.AddChart => "add_chart() returned a null pointer.",
        error.ChartAddSeries => "chart_add_series() returned a null pointer.",
        error.WriteRichString =>
        \\No Allocator provided to initWorkBook(), writeRichString() cannot be called,
        \\ > Provide Allocator or use writeRichStringNoAlloc() instead.
        ,
        error.AddTable =>
        \\No Allocator provided to initWorkBook(), addTables() cannot be called,
        \\ > Provide Allocator or use addTablesNoAlloc() instead.
        ,
        else => "unknown error, might not be an xlsxwriter error",
    };
}

const std = @import("std");
const c = @import("lxw");
const CString = @import("xlsxwriter.zig").CString;
const CStringArray = @import("xlsxwriter.zig").CStringArray;
